### ISSUE TITLE
EnableService monitor

### ISSUE THREAD

**Issue by dafe-corporate-sap** [SAP/redis-operator#59]
https://github.com/SAP/redis-operator/blob/62b230451bc6d20e7926029f59b0a6f4e24e3bec/pkg/operator/data/charts/redis/templates/servicemonitor.yaml#L24

operator itself doesn’t have it in its API:
https://github.com/SAP/redis-operator/blob/62b230451bc6d20e7926029f59b0a6f4e24e3bec/api/v1alpha1/types.go

Please expose ServiceMonitor to API of the operator.

**Comment by cbarbian-sap** [comment]
This would create a dependency on prometheus-operator.
I'm not sure if we should do this. If at all, then it should be switchable.

**Comment by dafe-corporate-sap** [comment]
Implemented
