### ISSUE TITLE
Upgrade helm chart

### ISSUE THREAD

**Issue by cbarbian-sap** [SAP/redis-operator#67]
We should update https://github.com/bitnami/charts/blob/main/bitnami/redis/Chart.yaml to 19.0.1 (or higher).
But before doing so it must be checked that the defaulted Redis appVersion in that chart (`Chart.yaml`) is not affected by the Redis license change.

**Comment by jaroslav-viravec** [comment]
Task has been done in PR =>  https://github.com/SAP/redis-operator/pull/75
redis components has been releases
new version of redis-operator (v0.1.29)
new version of redis-operator-helm (v0.1.32)
new version of redis-operator-cop (v0.1.45)
The changes has been rollouted to the cluster-setup and clusters and rollouted to the our stages ( dev, test, prod )

**Comment by jaroslav-viravec** [comment]
task done ✅
